// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e49ac35a-10dd-4cbf-9341-1130b2ffc6f4",
    "aws_cognito_region": "us-east-1",
    "aws_cognito_domain" : "bigdataaz2487.auth.us-east-1.amazoncognito.com",
    "aws_user_pools_id": "us-east-1_Kf76Jrf8D",
    "aws_user_pools_web_client_id": "46tg1m2f0te02kj6cti350urin",
    "aws_content_delivery_bucket": "bigdata-20181007142038--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://di6xn6v1ya3hq.cloudfront.net",
    "aws_cloud_logic_custom": [
        {
            "name": "chatbotapi",
            "endpoint": "https://2v5cw90m3a.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
